[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "same-origin"
        Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"
        Content-Security-Policy = "default-src 'self'; script-src 'self' 'sha256-ieoeWczDHkReVBsRBqaal5AFMlBtNjMzgwKvLqi/tSU=' 'sha256-f3s1giD9yOO/hoULY8FlCVZXm+Ovyb/BrtiOMiEIlJw=' 'sha256-7ajePByJHGyj20+a71HrWei+5FO3PKcFFmBgMBssfaM=' 'sha256-hVR3nYb42WzN5iXrInplpqO9CoXdHYAUWQZFsfirBLk=' 'sha256-bXiKq3nclDnX9cCknfWOzEGnEFP3Oq4BuKrPDox7WJI=' 'sha256-tAR+SbZJD5r03zQTNYcS/QgRyyS46+CFQSm0ldqwF4o=' 'sha256-qkc/dDEjMNvHppHMBkHBzBQXWsxjCm8pqRA6X4TQUSg=' 'sha256-ZswfTY7H35rbv8WC7NXBoiC7WNu86vSzCDChNWwZZDM='; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self'; form-action 'self'; frame-ancestors 'none'; base-uri 'self'; object-src 'none';"
